import React from 'react';
import * as ContentIcons from '@/shared/assets/icons/content';
import { type LucideIcon } from '@/shared/assets/icons/system';

// Small filled circle icon component
export const SmallFilledCircle: React.FC<{ className?: string }> = ({ className }) => (
  <svg
    viewBox="0 0 24 24"
    fill="currentColor"
    className={className}
    xmlns="http://www.w3.org/2000/svg"
  >
    <circle cx="12" cy="12" r="4" />
  </svg>
);

/**
 * Icon mapping for habit icons
 * Maps icon key strings to their corresponding Lucide icon components
 */
export const ICON_MAP: Record<string, LucideIcon | React.FC<{ className?: string }>> = {
  circle: SmallFilledCircle,
  dumbbell: ContentIcons.Dumbbell,
  book: ContentIcons.Book,
  coffee: ContentIcons.Coffee,
  zap: ContentIcons.Zap,
  heart: ContentIcons.Heart,
  droplet: ContentIcons.Droplet,
  apple: ContentIcons.Apple,
  moon: ContentIcons.Moon,
  smile: ContentIcons.Smile,
  checkCircle: ContentIcons.CheckCircle,
  target: ContentIcons.Target,
  music: ContentIcons.Music,
  camera: ContentIcons.Camera,
  brush: ContentIcons.Brush,
  code: ContentIcons.Code,
  briefcase: ContentIcons.Briefcase,
  users: ContentIcons.Users,
  phone: ContentIcons.Phone,
  mail: ContentIcons.Mail,
  bookmark: ContentIcons.Bookmark,
  lightbulb: ContentIcons.Lightbulb,
  star: ContentIcons.Star,
  clock: ContentIcons.Clock,
  calendar: ContentIcons.Calendar,
  award: ContentIcons.Award,
  gift: ContentIcons.Gift,
  leaf: ContentIcons.Leaf,
  sun: ContentIcons.Sun,
  cloud: ContentIcons.Cloud,
  helpCircle: ContentIcons.HelpCircle,
  // Дополнительные иконки
  bike: ContentIcons.Bike,
  mountain: ContentIcons.Mountain,
  flame: ContentIcons.Flame,
  wind: ContentIcons.Wind,
  globe: ContentIcons.Globe,
  home: ContentIcons.Home,
  map: ContentIcons.Map,
  compass: ContentIcons.Compass,
  navigation: ContentIcons.Navigation,
  flag: ContentIcons.Flag,
  rocket: ContentIcons.Rocket,
  plane: ContentIcons.Plane,
  car: ContentIcons.Car,
  train: ContentIcons.Train,
  ship: ContentIcons.Ship,
  package: ContentIcons.Package,
  shoppingCart: ContentIcons.ShoppingCart,
  shoppingBag: ContentIcons.ShoppingBag,
  dollarSign: ContentIcons.DollarSign,
  creditCard: ContentIcons.CreditCard,
  wallet: ContentIcons.Wallet,
  barChart: ContentIcons.BarChart,
  pieChart: ContentIcons.PieChart,
  activity: ContentIcons.Activity,
  battery: ContentIcons.Battery,
  wifi: ContentIcons.Wifi,
  radio: ContentIcons.Radio,
  tv: ContentIcons.Tv,
  film: ContentIcons.Film,
  image: ContentIcons.Image,
  video: ContentIcons.Video,
  headphones: ContentIcons.Headphones,
  mic: ContentIcons.Mic,
  messageCircle: ContentIcons.MessageCircle,
  messageSquare: ContentIcons.MessageSquare,
  inbox: ContentIcons.Inbox,
  send: ContentIcons.Send,
  download: ContentIcons.Download,
  upload: ContentIcons.Upload,
  fileText: ContentIcons.FileText,
  folder: ContentIcons.Folder,
  archive: ContentIcons.Archive,
  trash: ContentIcons.Trash2,
  save: ContentIcons.Save,
  // Еще 25 иконок для расширения до 100
  umbrella: ContentIcons.Umbrella,
  glasses: ContentIcons.Glasses,
  watch: ContentIcons.Watch,
  key: ContentIcons.Key,
  lock: ContentIcons.Lock,
  shield: ContentIcons.Shield,
  sword: ContentIcons.Sword,
  hammer: ContentIcons.Hammer,
  wrench: ContentIcons.Wrench,
  scissors: ContentIcons.Scissors,
  ruler: ContentIcons.Ruler,
  pencil: ContentIcons.Pencil,
  footprints: ContentIcons.Footprints,
  feather: ContentIcons.Feather,
  palette: ContentIcons.Palette,
  pizza: ContentIcons.Pizza,
  iceCream: ContentIcons.IceCream,
  cake: ContentIcons.Cake,
  cookie: ContentIcons.Cookie,
  fish: ContentIcons.Fish,
  dog: ContentIcons.Dog,
  cat: ContentIcons.Cat,
  bird: ContentIcons.Bird,
  treePine: ContentIcons.TreePine,
  flower: ContentIcons.Flower,
};

/**
 * Available icon options for the icon picker
 * Each option includes a key, label, and the icon component
 */
export const ICON_OPTIONS = [
  { key: 'circle', label: 'Базовое', Icon: SmallFilledCircle },
  { key: 'dumbbell', label: 'Тренировки', Icon: ContentIcons.Dumbbell },
  { key: 'book', label: 'Чтение', Icon: ContentIcons.Book },
  { key: 'coffee', label: 'Утренний ритуал', Icon: ContentIcons.Coffee },
  { key: 'zap', label: 'Энергия', Icon: ContentIcons.Zap },
  { key: 'heart', label: 'Здоровье', Icon: ContentIcons.Heart },
  { key: 'droplet', label: 'Вода', Icon: ContentIcons.Droplet },
  { key: 'apple', label: 'Питание', Icon: ContentIcons.Apple },
  { key: 'moon', label: 'Сон', Icon: ContentIcons.Moon },
  { key: 'smile', label: 'Медитация', Icon: ContentIcons.Smile },
  { key: 'checkCircle', label: 'Задачи', Icon: ContentIcons.CheckCircle },
  { key: 'target', label: 'Цели', Icon: ContentIcons.Target },
  { key: 'music', label: 'Музыка', Icon: ContentIcons.Music },
  { key: 'camera', label: 'Фото', Icon: ContentIcons.Camera },
  { key: 'brush', label: 'Творчество', Icon: ContentIcons.Brush },
  { key: 'code', label: 'Программирование', Icon: ContentIcons.Code },
  { key: 'briefcase', label: 'Работа', Icon: ContentIcons.Briefcase },
  { key: 'users', label: 'Социальное', Icon: ContentIcons.Users },
  { key: 'phone', label: 'Звонки', Icon: ContentIcons.Phone },
  { key: 'mail', label: 'Почта', Icon: ContentIcons.Mail },
  { key: 'bookmark', label: 'Обучение', Icon: ContentIcons.Bookmark },
  { key: 'lightbulb', label: 'Идеи', Icon: ContentIcons.Lightbulb },
  { key: 'star', label: 'Важное', Icon: ContentIcons.Star },
  { key: 'clock', label: 'Время', Icon: ContentIcons.Clock },
  { key: 'calendar', label: 'Планирование', Icon: ContentIcons.Calendar },
  { key: 'award', label: 'Достижения', Icon: ContentIcons.Award },
  { key: 'gift', label: 'Благодарность', Icon: ContentIcons.Gift },
  { key: 'leaf', label: 'Экология', Icon: ContentIcons.Leaf },
  { key: 'sun', label: 'Утро', Icon: ContentIcons.Sun },
  { key: 'cloud', label: 'Вечер', Icon: ContentIcons.Cloud },
  { key: 'helpCircle', label: 'Помощь', Icon: ContentIcons.HelpCircle },
  // Дополнительные иконки
  { key: 'bike', label: 'Велосипед', Icon: ContentIcons.Bike },
  { key: 'mountain', label: 'Горы', Icon: ContentIcons.Mountain },
  { key: 'flame', label: 'Огонь', Icon: ContentIcons.Flame },
  { key: 'wind', label: 'Ветер', Icon: ContentIcons.Wind },
  { key: 'globe', label: 'Глобус', Icon: ContentIcons.Globe },
  { key: 'home', label: 'Дом', Icon: ContentIcons.Home },
  { key: 'map', label: 'Карта', Icon: ContentIcons.Map },
  { key: 'compass', label: 'Компас', Icon: ContentIcons.Compass },
  { key: 'navigation', label: 'Навигация', Icon: ContentIcons.Navigation },
  { key: 'flag', label: 'Флаг', Icon: ContentIcons.Flag },
  { key: 'rocket', label: 'Ракета', Icon: ContentIcons.Rocket },
  { key: 'plane', label: 'Самолет', Icon: ContentIcons.Plane },
  { key: 'car', label: 'Машина', Icon: ContentIcons.Car },
  { key: 'train', label: 'Поезд', Icon: ContentIcons.Train },
  { key: 'ship', label: 'Корабль', Icon: ContentIcons.Ship },
  { key: 'package', label: 'Пакет', Icon: ContentIcons.Package },
  { key: 'shoppingCart', label: 'Корзина', Icon: ContentIcons.ShoppingCart },
  { key: 'shoppingBag', label: 'Сумка', Icon: ContentIcons.ShoppingBag },
  { key: 'dollarSign', label: 'Доллар', Icon: ContentIcons.DollarSign },
  { key: 'creditCard', label: 'Кредитная карта', Icon: ContentIcons.CreditCard },
  { key: 'wallet', label: 'Кошелек', Icon: ContentIcons.Wallet },
  { key: 'barChart', label: 'Гистограмма', Icon: ContentIcons.BarChart },
  { key: 'pieChart', label: 'Круговая диаграмма', Icon: ContentIcons.PieChart },
  { key: 'activity', label: 'Активность', Icon: ContentIcons.Activity },
  { key: 'battery', label: 'Батарея', Icon: ContentIcons.Battery },
  { key: 'wifi', label: 'Wi-Fi', Icon: ContentIcons.Wifi },
  { key: 'radio', label: 'Радио', Icon: ContentIcons.Radio },
  { key: 'tv', label: 'Телевизор', Icon: ContentIcons.Tv },
  { key: 'film', label: 'Фильм', Icon: ContentIcons.Film },
  { key: 'image', label: 'Изображение', Icon: ContentIcons.Image },
  { key: 'video', label: 'Видео', Icon: ContentIcons.Video },
  { key: 'headphones', label: 'Наушники', Icon: ContentIcons.Headphones },
  { key: 'mic', label: 'Микрофон', Icon: ContentIcons.Mic },
  { key: 'messageCircle', label: 'Сообщение', Icon: ContentIcons.MessageCircle },
  { key: 'messageSquare', label: 'Сообщение', Icon: ContentIcons.MessageSquare },
  { key: 'inbox', label: 'Входящие', Icon: ContentIcons.Inbox },
  { key: 'send', label: 'Отправить', Icon: ContentIcons.Send },
  { key: 'download', label: 'Скачать', Icon: ContentIcons.Download },
  { key: 'upload', label: 'Загрузить', Icon: ContentIcons.Upload },
  { key: 'fileText', label: 'Файл', Icon: ContentIcons.FileText },
  { key: 'folder', label: 'Папка', Icon: ContentIcons.Folder },
  { key: 'archive', label: 'Архив', Icon: ContentIcons.Archive },
  { key: 'trash', label: 'Корзина', Icon: ContentIcons.Trash2 },
  { key: 'save', label: 'Сохранить', Icon: ContentIcons.Save },
  // Еще 25 иконок для расширения до 100
  { key: 'umbrella', label: 'Зонт', Icon: ContentIcons.Umbrella },
  { key: 'glasses', label: 'Очки', Icon: ContentIcons.Glasses },
  { key: 'watch', label: 'Часы', Icon: ContentIcons.Watch },
  { key: 'key', label: 'Ключ', Icon: ContentIcons.Key },
  { key: 'lock', label: 'Замок', Icon: ContentIcons.Lock },
  { key: 'shield', label: 'Щит', Icon: ContentIcons.Shield },
  { key: 'sword', label: 'Меч', Icon: ContentIcons.Sword },
  { key: 'hammer', label: 'Молоток', Icon: ContentIcons.Hammer },
  { key: 'wrench', label: 'Гаечный ключ', Icon: ContentIcons.Wrench },
  { key: 'scissors', label: 'Ножницы', Icon: ContentIcons.Scissors },
  { key: 'ruler', label: 'Линейка', Icon: ContentIcons.Ruler },
  { key: 'pencil', label: 'Карандаш', Icon: ContentIcons.Pencil },
  { key: 'footprints', label: 'Следы', Icon: ContentIcons.Footprints },
  { key: 'feather', label: 'Перо', Icon: ContentIcons.Feather },
  { key: 'palette', label: 'Палитра', Icon: ContentIcons.Palette },
  { key: 'pizza', label: 'Пицца', Icon: ContentIcons.Pizza },
  { key: 'iceCream', label: 'Мороженое', Icon: ContentIcons.IceCream },
  { key: 'cake', label: 'Торт', Icon: ContentIcons.Cake },
  { key: 'cookie', label: 'Печенье', Icon: ContentIcons.Cookie },
  { key: 'fish', label: 'Рыба', Icon: ContentIcons.Fish },
  { key: 'dog', label: 'Собака', Icon: ContentIcons.Dog },
  { key: 'cat', label: 'Кошка', Icon: ContentIcons.Cat },
  { key: 'bird', label: 'Птица', Icon: ContentIcons.Bird },
  { key: 'treePine', label: 'Сосна', Icon: ContentIcons.TreePine },
  { key: 'flower', label: 'Цветок', Icon: ContentIcons.Flower },
] as const;