import React from 'react';
import {
  Dumbbell, Book, Coffee, Zap, Heart, Droplet, Apple, Moon, Smile, CheckCircle,
  Target, Music, Camera, Brush, Code, Briefcase, Users, Phone, Mail, Bookmark,
  Lightbulb, Star, Clock, Calendar, Award, Gift, Leaf, Sun, Cloud, HelpCircle,
  // Дополнительные иконки
  Bike, Mountain, Flame, Wind, Globe, Home, Map, Compass, Navigation, Flag,
  Rocket, Plane, Car, Train, Ship, Package, ShoppingCart, ShoppingBag, DollarSign, CreditCard,
  Wallet, BarChart, PieChart, Activity, Battery, Wifi, Radio, Tv,
  Film, Image, Video, Headphones, Mic, MessageCircle, MessageSquare, Inbox, Send,
  Download, Upload, FileText, Folder, Archive, Trash, Save,
  // Еще 25 иконок для расширения до 100
  Umbrella, Glasses, Watch, Key, Lock, Shield, Sword, Hammer, Wrench, Scissors,
  Ruler, Pencil, Footprints, Feather, Palette, Pizza, IceCream, Cake, Cookie, Fish,
  Dog, Cat, Bird, TreePine, Flower,
  type LucideIcon
} from '@/shared/icons';

// Export DragHandle from the icons folder
export { DragHandle } from '@/shared/icons';

// Small filled circle icon component
export const SmallFilledCircle: React.FC<{ className?: string }> = ({ className }) => (
  <svg
    viewBox="0 0 24 24"
    fill="currentColor"
    className={className}
    xmlns="http://www.w3.org/2000/svg"
  >
    <circle cx="12" cy="12" r="4" />
  </svg>
);

/**
 * Icon mapping for habit icons
 * Maps icon key strings to their corresponding Lucide icon components
 */
export const ICON_MAP: Record<string, LucideIcon | React.FC<{ className?: string }>> = {
  circle: SmallFilledCircle,
  dumbbell: Dumbbell,
  book: Book,
  coffee: Coffee,
  zap: Zap,
  heart: Heart,
  droplet: Droplet,
  apple: Apple,
  moon: Moon,
  smile: Smile,
  checkCircle: CheckCircle,
  target: Target,
  music: Music,
  camera: Camera,
  brush: Brush,
  code: Code,
  briefcase: Briefcase,
  users: Users,
  phone: Phone,
  mail: Mail,
  bookmark: Bookmark,
  lightbulb: Lightbulb,
  star: Star,
  clock: Clock,
  calendar: Calendar,
  award: Award,
  gift: Gift,
  leaf: Leaf,
  sun: Sun,
  cloud: Cloud,
  helpCircle: HelpCircle,
  // Дополнительные иконки
  bike: Bike,
  mountain: Mountain,
  flame: Flame,
  wind: Wind,
  globe: Globe,
  home: Home,
  map: Map,
  compass: Compass,
  navigation: Navigation,
  flag: Flag,
  rocket: Rocket,
  plane: Plane,
  car: Car,
  train: Train,
  ship: Ship,
  package: Package,
  shoppingCart: ShoppingCart,
  shoppingBag: ShoppingBag,
  dollarSign: DollarSign,
  creditCard: CreditCard,
  wallet: Wallet,
  barChart: BarChart,
  pieChart: PieChart,
  activity: Activity,
  battery: Battery,
  wifi: Wifi,
  radio: Radio,
  tv: Tv,
  film: Film,
  image: Image,
  video: Video,
  headphones: Headphones,
  mic: Mic,
  messageCircle: MessageCircle,
  messageSquare: MessageSquare,
  inbox: Inbox,
  send: Send,
  download: Download,
  upload: Upload,
  fileText: FileText,
  folder: Folder,
  archive: Archive,
  trash: Trash,
  save: Save,
  // Еще 25 иконок для расширения до 100
  umbrella: Umbrella,
  glasses: Glasses,
  watch: Watch,
  key: Key,
  lock: Lock,
  shield: Shield,
  sword: Sword,
  hammer: Hammer,
  wrench: Wrench,
  scissors: Scissors,
  ruler: Ruler,
  pencil: Pencil,
  footprints: Footprints,
  feather: Feather,
  palette: Palette,
  pizza: Pizza,
  iceCream: IceCream,
  cake: Cake,
  cookie: Cookie,
  fish: Fish,
  dog: Dog,
  cat: Cat,
  bird: Bird,
  treePine: TreePine,
  flower: Flower,
};

/**
 * Available icon options for the icon picker
 * Each option includes a key, label, and the icon component
 */
export const ICON_OPTIONS = [
  { key: 'circle', label: 'Базовое', Icon: SmallFilledCircle },
  { key: 'dumbbell', label: 'Тренировки', Icon: Dumbbell },
  { key: 'book', label: 'Чтение', Icon: Book },
  { key: 'coffee', label: 'Утренний ритуал', Icon: Coffee },
  { key: 'zap', label: 'Энергия', Icon: Zap },
  { key: 'heart', label: 'Здоровье', Icon: Heart },
  { key: 'droplet', label: 'Вода', Icon: Droplet },
  { key: 'apple', label: 'Питание', Icon: Apple },
  { key: 'moon', label: 'Сон', Icon: Moon },
  { key: 'smile', label: 'Медитация', Icon: Smile },
  { key: 'checkCircle', label: 'Задачи', Icon: CheckCircle },
  { key: 'target', label: 'Цели', Icon: Target },
  { key: 'music', label: 'Музыка', Icon: Music },
  { key: 'camera', label: 'Фото', Icon: Camera },
  { key: 'brush', label: 'Творчество', Icon: Brush },
  { key: 'code', label: 'Программирование', Icon: Code },
  { key: 'briefcase', label: 'Работа', Icon: Briefcase },
  { key: 'users', label: 'Социальное', Icon: Users },
  { key: 'phone', label: 'Звонки', Icon: Phone },
  { key: 'mail', label: 'Почта', Icon: Mail },
  { key: 'bookmark', label: 'Обучение', Icon: Bookmark },
  { key: 'lightbulb', label: 'Идеи', Icon: Lightbulb },
  { key: 'star', label: 'Важное', Icon: Star },
  { key: 'clock', label: 'Время', Icon: Clock },
  { key: 'calendar', label: 'Планирование', Icon: Calendar },
  { key: 'award', label: 'Достижения', Icon: Award },
  { key: 'gift', label: 'Благодарность', Icon: Gift },
  { key: 'leaf', label: 'Экология', Icon: Leaf },
  { key: 'sun', label: 'Утро', Icon: Sun },
  { key: 'cloud', label: 'Вечер', Icon: Cloud },
  { key: 'helpCircle', label: 'Помощь', Icon: HelpCircle },
  // Дополнительные иконки
  { key: 'bike', label: 'Велосипед', Icon: Bike },
  { key: 'mountain', label: 'Горы', Icon: Mountain },
  { key: 'flame', label: 'Огонь', Icon: Flame },
  { key: 'wind', label: 'Ветер', Icon: Wind },
  { key: 'globe', label: 'Глобус', Icon: Globe },
  { key: 'home', label: 'Дом', Icon: Home },
  { key: 'map', label: 'Карта', Icon: Map },
  { key: 'compass', label: 'Компас', Icon: Compass },
  { key: 'navigation', label: 'Навигация', Icon: Navigation },
  { key: 'flag', label: 'Флаг', Icon: Flag },
  { key: 'rocket', label: 'Ракета', Icon: Rocket },
  { key: 'plane', label: 'Самолет', Icon: Plane },
  { key: 'car', label: 'Машина', Icon: Car },
  { key: 'train', label: 'Поезд', Icon: Train },
  { key: 'ship', label: 'Корабль', Icon: Ship },
  { key: 'package', label: 'Пакет', Icon: Package },
  { key: 'shoppingCart', label: 'Корзина', Icon: ShoppingCart },
  { key: 'shoppingBag', label: 'Сумка', Icon: ShoppingBag },
  { key: 'dollarSign', label: 'Доллар', Icon: DollarSign },
  { key: 'creditCard', label: 'Кредитная карта', Icon: CreditCard },
  { key: 'wallet', label: 'Кошелек', Icon: Wallet },
  { key: 'barChart', label: 'Гистограмма', Icon: BarChart },
  { key: 'pieChart', label: 'Круговая диаграмма', Icon: PieChart },
  { key: 'activity', label: 'Активность', Icon: Activity },
  { key: 'battery', label: 'Батарея', Icon: Battery },
  { key: 'wifi', label: 'Wi-Fi', Icon: Wifi },
  { key: 'radio', label: 'Радио', Icon: Radio },
  { key: 'tv', label: 'Телевизор', Icon: Tv },
  { key: 'film', label: 'Фильм', Icon: Film },
  { key: 'image', label: 'Изображение', Icon: Image },
  { key: 'video', label: 'Видео', Icon: Video },
  { key: 'headphones', label: 'Наушники', Icon: Headphones },
  { key: 'mic', label: 'Микрофон', Icon: Mic },
  { key: 'messageCircle', label: 'Сообщение', Icon: MessageCircle },
  { key: 'messageSquare', label: 'Сообщение', Icon: MessageSquare },
  { key: 'inbox', label: 'Входящие', Icon: Inbox },
  { key: 'send', label: 'Отправить', Icon: Send },
  { key: 'download', label: 'Скачать', Icon: Download },
  { key: 'upload', label: 'Загрузить', Icon: Upload },
  { key: 'fileText', label: 'Файл', Icon: FileText },
  { key: 'folder', label: 'Папка', Icon: Folder },
  { key: 'archive', label: 'Архив', Icon: Archive },
  { key: 'trash', label: 'Корзина', Icon: Trash },
  { key: 'save', label: 'Сохранить', Icon: Save },
  // Еще 25 иконок для расширения до 100
  { key: 'umbrella', label: 'Зонт', Icon: Umbrella },
  { key: 'glasses', label: 'Очки', Icon: Glasses },
  { key: 'watch', label: 'Часы', Icon: Watch },
  { key: 'key', label: 'Ключ', Icon: Key },
  { key: 'lock', label: 'Замок', Icon: Lock },
  { key: 'shield', label: 'Щит', Icon: Shield },
  { key: 'sword', label: 'Меч', Icon: Sword },
  { key: 'hammer', label: 'Молоток', Icon: Hammer },
  { key: 'wrench', label: 'Гаечный ключ', Icon: Wrench },
  { key: 'scissors', label: 'Ножницы', Icon: Scissors },
  { key: 'ruler', label: 'Линейка', Icon: Ruler },
  { key: 'pencil', label: 'Карандаш', Icon: Pencil },
  { key: 'footprints', label: 'Следы', Icon: Footprints },
  { key: 'feather', label: 'Перо', Icon: Feather },
  { key: 'palette', label: 'Палитра', Icon: Palette },
  { key: 'pizza', label: 'Пицца', Icon: Pizza },
  { key: 'iceCream', label: 'Мороженое', Icon: IceCream },
  { key: 'cake', label: 'Торт', Icon: Cake },
  { key: 'cookie', label: 'Печенье', Icon: Cookie },
  { key: 'fish', label: 'Рыба', Icon: Fish },
  { key: 'dog', label: 'Собака', Icon: Dog },
  { key: 'cat', label: 'Кошка', Icon: Cat },
  { key: 'bird', label: 'Птица', Icon: Bird },
  { key: 'treePine', label: 'Сосна', Icon: TreePine },
  { key: 'flower', label: 'Цветок', Icon: Flower },
] as const;

/**
 * Default icon key used when no icon is specified
 */
export const DEFAULT_ICON_KEY = 'circle';

/**
 * Number of icons to display per page in the icon picker
 */
export const ICONS_PER_PAGE = 10;